// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQ3RzbShSRa3c1p6Bdbkv_HIZQC462Fs',
    appId: '1:157796386001:android:7abcdcda11a7af3ddf71f0',
    messagingSenderId: '157796386001',
    projectId: 'footapp-c17ca',
    databaseURL: 'https://footapp-c17ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'footapp-c17ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrohm7ztdXrofqbv7TQphT1CfjMQbM0RM',
    appId: '1:157796386001:ios:15b124e1dd89c730df71f0',
    messagingSenderId: '157796386001',
    projectId: 'footapp-c17ca',
    databaseURL: 'https://footapp-c17ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'footapp-c17ca.firebasestorage.app',
    iosBundleId: 'com.freeplay.yourleague.yourleague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwwAGUeHsTkh-rzTB4dlvuqmRP31Tf1PE',
    appId: '1:157796386001:web:5ccc2d6ad95f80a0df71f0',
    messagingSenderId: '157796386001',
    projectId: 'footapp-c17ca',
    authDomain: 'footapp-c17ca.firebaseapp.com',
    databaseURL: 'https://footapp-c17ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'footapp-c17ca.firebasestorage.app',
    measurementId: 'G-D9TKG8WXRM',
  );
}
